version: '3'
services:
  app:
    build: 
        context: . 
        dockerfile: DockerFile
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root
